spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.config.import=\
  classpath:application-admin.properties,\
  optional:file:${FLINT_CONFIG_DIR:./config}/application.properties,\
  optional:file:${FLINT_CONFIG_DIR:./config}/application-local.properties
