# One-time setup: connect to your local MySQL (same password as MySQL Workbench).
# Creates flintdb and writes local-db.properties so the backend uses MySQL instead of H2 fallback.
$ErrorActionPreference = "Stop"
$mysql = "C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe"
$root = Split-Path $PSScriptRoot -Parent
if (-not (Test-Path $mysql)) {
    Write-Error "MySQL client not found at $mysql"
}

$secure = Read-Host "MySQL root password (same as MySQL Workbench)" -AsSecureString
$bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
$password = [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)

$test = & $mysql -u root "-p$password" -e "SELECT 1;" 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "MySQL login failed: $test"
}

& $mysql -u root "-p$password" -e "CREATE DATABASE IF NOT EXISTS flintdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
if ($LASTEXITCODE -ne 0) { Write-Error "Could not create flintdb" }

$props = @(
    "# Generated by scripts/setup-local-db.ps1 — do not commit",
    "app.db.mysql-fallback=false",
    "spring.datasource.password=$password"
)
$out = Join-Path $root "local-db.properties"
$props | Set-Content -Path $out -Encoding UTF8
Write-Host "Wrote $out"
Write-Host "Restart the backend — it will use local MySQL (flintdb). Import a dump if you need existing data."
