package com.ecommerce.adminbackend.util;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class CustomerOrderHistoryHtmlBuilder {

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("dd MMM yyyy", Locale.ENGLISH);

    private CustomerOrderHistoryHtmlBuilder() {
    }

    public static String build(Map<String, Object> customer, List<Map<String, Object>> orders) {
        String name = escape(stringAt(customer, "name", "Customer"));
        String customerId = escape(stringAt(customer, "id", "—"));
        long orderCount = numberAt(customer, "orderCount");
        String totalSpent = escape(formatAmount(customer.get("totalSpent")));
        String lastOrder = escape(formatDate(customer.get("lastOrderAt")));

        StringBuilder rows = new StringBuilder();
        for (Map<String, Object> order : orders) {
            rows.append("<tr>")
                    .append("<td>").append(escape(stringAt(order, "orderNumber", "—"))).append("</td>")
                    .append("<td>").append(escape(formatDate(order.get("createdAt")))).append("</td>")
                    .append("<td>").append(escape(String.valueOf(numberAt(order, "itemCount")))).append("</td>")
                    .append("<td>").append(escape(formatAmount(order.get("totalAmount")))).append("</td>")
                    .append("<td>").append(escape(stringAt(order, "paymentMethod", "—"))).append("</td>")
                    .append("<td>").append(escape(stringAt(order, "orderStatus", "—"))).append("</td>")
                    .append("</tr>");
        }

        if (rows.isEmpty()) {
            rows.append("<tr><td colspan=\"6\" style=\"text-align:center;color:#6B7280;\">No orders found</td></tr>");
        }

        return """
                <!DOCTYPE html>
                <html>
                  <head>
                    <meta charset="UTF-8" />
                    <style>
                      body { font-family: Helvetica, Arial, sans-serif; padding: 24px; color: #374151; }
                      h1 { color: #151D4F; margin: 0 0 4px; font-size: 24px; }
                      h2 { color: #151D4F; margin: 28px 0 12px; font-size: 16px; }
                      .info-box { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px 16px; margin-top: 16px; }
                      .info-box p { margin: 4px 0; font-size: 13px; }
                      table { width: 100%%; border-collapse: collapse; margin-top: 8px; font-size: 12px; }
                      th, td { border: 1px solid #e5e7eb; padding: 10px 8px; text-align: left; }
                      th { background: #f3f4f6; font-weight: 700; color: #1C2B4A; }
                      tr:nth-child(even) td { background: #fafafa; }
                      .footer { margin-top: 28px; text-align: center; font-size: 10px; color: #9CA3AF; }
                    </style>
                  </head>
                  <body>
                    <h1>Customer Order History</h1>
                    <div class="info-box">
                      <p><strong>Customer Name:</strong> %s</p>
                      <p><strong>Customer ID:</strong> %s</p>
                      <p><strong>Orders:</strong> %d</p>
                      <p><strong>Total Spent:</strong> %s</p>
                      <p><strong>Last Order:</strong> %s</p>
                    </div>
                    <h2>Order History</h2>
                    <table>
                      <thead>
                        <tr>
                          <th>Order #</th>
                          <th>Date</th>
                          <th>Items</th>
                          <th>Amount</th>
                          <th>Payment</th>
                          <th>Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        %s
                      </tbody>
                    </table>
                    <p class="footer">Generated by Flint &amp; Thread Admin Panel</p>
                  </body>
                </html>
                """.formatted(name, customerId, orderCount, totalSpent, lastOrder, rows);
    }

    private static String stringAt(Map<String, Object> map, String key, String fallback) {
        if (map == null) {
            return fallback;
        }
        Object value = map.get(key);
        if (value == null) {
            return fallback;
        }
        String text = String.valueOf(value).trim();
        return text.isEmpty() ? fallback : text;
    }

    private static long numberAt(Map<String, Object> map, String key) {
        if (map == null) {
            return 0L;
        }
        Object value = map.get(key);
        if (value instanceof Number number) {
            return number.longValue();
        }
        if (value == null) {
            return 0L;
        }
        try {
            return Long.parseLong(String.valueOf(value));
        } catch (NumberFormatException ex) {
            return 0L;
        }
    }

    private static String formatAmount(Object value) {
        if (value == null) {
            return "₹0.00";
        }
        if (value instanceof BigDecimal decimal) {
            return "₹" + decimal.setScale(2, java.math.RoundingMode.HALF_UP);
        }
        if (value instanceof Number number) {
            return String.format(Locale.ENGLISH, "₹%.2f", number.doubleValue());
        }
        return "₹" + value;
    }

    private static String formatDate(Object value) {
        if (value == null) {
            return "N/A";
        }
        if (value instanceof LocalDateTime dateTime) {
            return DATE_FMT.format(dateTime);
        }
        String text = String.valueOf(value).trim();
        return text.isEmpty() ? "N/A" : text;
    }

    private static String escape(String value) {
        if (value == null) {
            return "";
        }
        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }
}
